@startwbs
skinparam backgroundColor ivory

+ Drone Control
 + Gyro Control
  + Align with vector
 + Thruster Control
  + Control thruster in direction
  + Calculate thrust in direction
  + Apply forch in direction
 + Thruster & Gyro Integration
  + Maintain foward velocity
  + Determin stopping speed
  + Flip and burn (emergancy stop)
 + Basic Routing
  + Waypoint setup
  + Navagate to waypoint
 + Camera Integration
  + Object detection
  + Object boundary location
 + Advanced Routing
  + Navagate around objects
 + Basic Docking
@endwbs
