package DroneControl {

    package utility {
        enum Orientation {
            Up
            Down
            Backward
            Forward
            Right
            Left

            +Inverse()
            +CalcVelocity(Vector3D velocity)
        }

        interface AutoControl {
            DisableAuto()
        }

        package Task {

            enum action_tpye {
                GoTo
                Follow
            }

            abstract DroneAction {
                const action_tpye type

                {abstract} action_tpye get_type()
                {abstract} string Serialize()
                {abstract} bool Deserialization(string objective)
            }

            class GoTo {
                const type = action_tpye.GoTo

                List<Vector3D> route
                tolorance = 10

                GoTo(Vector3D target, float tolorance = 5)
                GoTo(string objective)
                bool Complete()
                Vector3D Next_Point()
                Add_Point(Vector3D point)
            }     

            class Task {
                List<DroneAction> actions

                DroneAction Get_Next_Action()
                bool Action_Complete()
                Add_Action(DroneAction action)
                Add_Action(String action)
            }

            GoTo .. DroneAction
            Task <-- GoTo : Contains
        }
    }

    package Gyro {
        class GyroControl <AutoControl>{
            -List<IMyGyro> ship_gyros

            bool OrientShip(\n\
            Orientation direction,\n\
            Vector3D target,\n\
            IMyTerminalBlock orientation_block,\n\
            double gyro_power = 0.9,\n\
            float min_angle = 5.0f)

        }
    }

    package Thruster {
        enum velocity_state
        {
            Moving
            Holding
        }

        class ThrusterControl <AutoControl>{
            
            +Vector3D velocity
            +Vector3D stopping_distances
            #velocity_state State
            -List<IMyThrust> ship_thrusters

            -void SetVelocity(\n\
            double target,\n\
            Orientation direction)
            -AppleAcceleration(\n\
            double acceleration,\n\
            Orientation direction)
            -ApplyForce(\n\
            double force,\n\
            Orientation direction)
            -GetMaxDirectionalForce(Orientation direction)
            -EnableAllThrusers()
            -OverideThrusters(\n\
            float percent,\n\
            Orientation direction)
            -DisableAuto()
        }
    }

    class DroneControl <AutoControl>{
        Task current_task
        
        GyroControl gyros
        ThrusterControl thrusters

        Vector3D get_local_velocity()
        Vector3D current_location()

        void Set_Task(Task task)
        GoTo(Vector3D Location)

        run()
    }

    DroneControl <-- ThrusterControl
    DroneControl <-- GyroControl
    DroneControl <-- Task : Recives
}
