@startuml
left to right direction
skinparam packageStyle rectangle

:user:
:drone controler: as Drone

rectangle Task {
    user -- (Create Task)
    (Create Task) .right. (Add Actions)
}

(Create Task) -- Drone : Get task object
@enduml